const productos = [{imagen: '🥔', tipo: 'verdura', codigo: 1, nombre: 'Papa', precio: 200},
                   {imagen: '🥬', tipo: 'verdura', codigo: 2, nombre: 'Lechuga', precio: 450},
                   {imagen: '🍅', tipo: 'verdura', codigo: 3, nombre: 'Tomate', precio: 600},
                   {imagen: '🥕', tipo: 'verdura', codigo: 4, nombre: 'Zanahoria', precio: 150},
                   {imagen: '🧅', tipo: 'verdura', codigo: 5, nombre: 'Cebolla', precio: 275},
                   {imagen: '🫑', tipo: 'verdura', codigo: 6, nombre: 'Morron', precio: 780},
                   {imagen: '🧄', tipo: 'verdura', codigo: 7, nombre: 'Ajo', precio: 100},
                   {imagen: '🍆', tipo: 'verdura', codigo: 8, nombre: 'Berenjena', precio: 200},
                   {imagen: '🌶️', tipo: 'verdura', codigo: 9, nombre: 'Aji', precio: 1500},
                   {imagen: '🥦', tipo: 'verdura', codigo: 10, nombre: 'Brocoli', precio: 250},
                   {imagen: '🌽', tipo: 'verdura', codigo: 11, nombre: 'Choclo', precio: 80},
                   {imagen: '🥑', tipo: 'verdura', codigo: 12, nombre: 'Palta', precio: 1280},
                   {imagen: '🥒', tipo: 'verdura', codigo: 13, nombre: 'Pepino', precio: 460},
                   {imagen: '🍑', tipo: 'fruta', codigo: 14, nombre: 'Durazno', precio: 650},
                   {imagen: '🍎', tipo: 'fruta', codigo: 15, nombre: 'Manzana Roja', precio: 810},
                   {imagen: '🍌', tipo: 'fruta', codigo: 16, nombre: 'Banana', precio: 500},
                   {imagen: '🍊', tipo: 'fruta', codigo: 17, nombre: 'Naranja', precio: 320},
                   {imagen: '🍓', tipo: 'fruta', codigo: 18, nombre: 'Frutilla', precio: 600},
                   {imagen: '🍍', tipo: 'fruta', codigo: 19, nombre: 'Anana en Piña', precio: 540},
                   {imagen: '🍐', tipo: 'fruta', codigo: 20, nombre: 'Pera', precio: 320},
                   {imagen: '🍒', tipo: 'fruta', codigo: 21, nombre: 'Cereza', precio: 780},
                   {imagen: '🍋', tipo: 'fruta', codigo: 22, nombre: 'Limón', precio: 950},
                   {imagen: '🍇', tipo: 'fruta', codigo: 23, nombre: 'Uva', precio: 650},
                   {imagen: '🥝', tipo: 'fruta', codigo: 24, nombre: 'Kiwi', precio: 430},
                   {imagen: '🍉', tipo: 'fruta', codigo: 25, nombre: 'Sandia', precio: 300}]